import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        secondary: "#4cd7f6",
        primary: "#c0c1ff",
        "on-primary-fixed": "#07006c",
        "error-container": "#93000a",
        "surface-container": "#1b202b",
        outline: "#908fa0",
        "on-tertiary-fixed-variant": "#703700",
        "secondary-container": "#03b5d3",
        "secondary-fixed": "#acedff",
        "tertiary-fixed": "#ffdcc5",
        "tertiary-container": "#d97721",
        "on-primary-fixed-variant": "#2f2ebe",
        "surface-container-low": "#171c27",
        "primary-fixed-dim": "#c0c1ff",
        "on-background": "#dee2f2",
        "surface-dim": "#0e131e",
        "on-error-container": "#ffdad6",
        "on-secondary": "#003640",
        "on-tertiary-container": "#452000",
        "on-tertiary": "#4f2500",
        "on-secondary-container": "#00424e",
        "on-error": "#690005",
        "inverse-on-surface": "#2b303c",
        "surface-container-lowest": "#090e19",
        "on-surface-variant": "#c7c4d7",
        "primary-fixed": "#e1e0ff",
        "surface-tint": "#c0c1ff",
        surface: "#0e131e",
        "on-tertiary-fixed": "#301400",
        "primary-container": "#8083ff",
        "outline-variant": "#464554",
        "on-secondary-fixed-variant": "#004e5c",
        "on-primary-container": "#0d0096",
        "on-primary": "#1000a9",
        background: "#0e131e",
        "inverse-surface": "#dee2f2",
        error: "#ffb4ab",
        "secondary-fixed-dim": "#4cd7f6",
        "surface-container-highest": "#303541",
        tertiary: "#ffb783",
        "on-secondary-fixed": "#001f26",
        "inverse-primary": "#494bd6",
        "surface-container-high": "#252a35",
        "tertiary-fixed-dim": "#ffb783",
        "on-surface": "#dee2f2",
        "surface-variant": "#303541",
        "surface-bright": "#343945",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        xs: "4px",
        xl: "40px",
        sm: "8px",
        "sidebar-width": "260px",
        md: "16px",
        lg: "24px",
        base: "4px",
        "container-max": "1440px",
      },
      fontFamily: {
        "headline-sm": ["Geist"],
        "mono-code": ["jetbrainsMono"],
        "label-md": ["Geist"],
        "display-lg": ["Geist"],
        "headline-md": ["Geist"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "body-sm": ["Inter"],
      },
      fontSize: {
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "mono-code": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["13px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
};
export default config;
