import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: '#000000',
        'on-primary': '#ffffff',
        'primary-container': '#222222',
        'on-primary-container': '#ffffff',
        'inverse-primary': '#ffffff',
        secondary: '#000000',
        'on-secondary': '#ffffff',
        'secondary-container': '#f3f3f3',
        'on-secondary-container': '#000000',
        tertiary: '#000000',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#eeeeee',
        'on-tertiary-container': '#000000',
        error: '#ff0000',
        'on-error': '#ffffff',
        'error-container': '#ffcccc',
        'on-error-container': '#aa0000',
        'primary-fixed': '#000000',
        'primary-fixed-dim': '#111111',
        'on-primary-fixed': '#ffffff',
        'on-primary-fixed-variant': '#dddddd',
        'secondary-fixed': '#000000',
        'secondary-fixed-dim': '#222222',
        'on-secondary-fixed': '#ffffff',
        'on-secondary-fixed-variant': '#cccccc',
        'tertiary-fixed': '#000000',
        'tertiary-fixed-dim': '#333333',
        'on-tertiary-fixed': '#ffffff',
        'on-tertiary-fixed-variant': '#bbbbbb',
        background: '#ffffff',
        'on-background': '#000000',
        'surface-variant': '#f6f6f6',
        'powder-blue': '#f3f3f3',
        'alice-blue': '#fafafa',
        'neutral-grey-blue': '#888888',
      },
      borderRadius: {
        sm: "0.5rem",
        DEFAULT: "1rem",
        md: "1.5rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        unit: "8px",
        gutter: "24px",
        "margin-mobile": "20px",
        "margin-desktop": "40px",
        "container-max": "1200px",
      },
      fontFamily: {
        "headline-lg": ["Inter", "system-ui", "sans-serif"],
        "headline-md": ["Inter", "system-ui", "sans-serif"],
        "body-lg": ["Inter", "system-ui", "sans-serif"],
        "body-md": ["Inter", "system-ui", "sans-serif"],
        "label-md": ["Inter", "system-ui", "sans-serif"],
        "label-sm": ["Inter", "system-ui", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["36px", { lineHeight: "44px", fontWeight: "700", letterSpacing: "-0.02em" }],
        "headline-lg-mobile": ["28px", { lineHeight: "34px", fontWeight: "700", letterSpacing: "-0.01em" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "700", letterSpacing: "0.02em" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
};
export default config;
