import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: '#87ceeb',
        'on-primary': '#ffffff',
        'primary-container': '#87ceeb',
        'on-primary-container': '#005870',
        'inverse-primary': '#89d0ed',
        secondary: '#37656b',
        'on-secondary': '#ffffff',
        'secondary-container': '#b8e8ee',
        'on-secondary-container': '#3b6a6f',
        tertiary: '#575f65',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#bdc5cc',
        'on-tertiary-container': '#4a5258',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#baeaff',
        'primary-fixed-dim': '#89d0ed',
        'on-primary-fixed': '#001f29',
        'on-primary-fixed-variant': '#004d62',
        'secondary-fixed': '#bbebf1',
        'secondary-fixed-dim': '#9fcfd5',
        'on-secondary-fixed': '#001f23',
        'on-secondary-fixed-variant': '#1d4d53',
        'tertiary-fixed': '#dbe4ea',
        'tertiary-fixed-dim': '#bfc8ce',
        'on-tertiary-fixed': '#151d22',
        'on-tertiary-fixed-variant': '#40484d',
        background: '#f9f9ff',
        'on-background': '#111c2c',
        'surface-variant': '#d8e3fa',
        'powder-blue': '#B0E0E6',
        'alice-blue': '#F0F8FF',
        'neutral-grey-blue': '#4A5568',
      },
      borderRadius: {
        sm: "0.5rem",
        DEFAULT: "1rem",
        md: "1.5rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        unit: "8px",
        gutter: "24px",
        "margin-mobile": "20px",
        "margin-desktop": "40px",
        "container-max": "1200px",
      },
      fontFamily: {
        "headline-lg": ["Quicksand"],
        "headline-md": ["Quicksand"],
        "body-lg": ["Nunito Sans"],
        "body-md": ["Nunito Sans"],
        "label-md": ["Nunito Sans"],
        "label-sm": ["Nunito Sans"],
      },
      fontSize: {
        "headline-lg": ["36px", { lineHeight: "44px", fontWeight: "700", letterSpacing: "-0.02em" }],
        "headline-lg-mobile": ["28px", { lineHeight: "34px", fontWeight: "700", letterSpacing: "-0.01em" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "700", letterSpacing: "0.02em" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
};
export default config;
